// editor/src/renderer/component/board.tsx
import * as React from 'react';

import { Option } from 'monapt';

import * as Common from '../../common';
import { ActionDispatcher } from '../container/board';

import Input from '@material-ui/core/Input';

interface SquareProps {
	square: Common.Square;
	pos: Common.Pos;
}

class Square extends React.Component<SquareProps> {
	render () {
		let color = this.props.square.agent.match({
			Some: color => {
				if (color == Common.Color.Red)
					return 'd32f2f';
				else
					return '303F9F';
			},
			None: () => 'FFFFFF'
		});
		let style = {
			backgroundColor: color,
			height: '7vh',
			width: '7vh',
			border: '1px solid #000',
			marginRight:  '-1px',
			marginTop: '-1px'
		};
		return (
			// float:leftの指定
			<div className='square' style={style}>
				<Input fullWidth/>
			</div>
		);
	}
}

interface BoardProps {
	board: Common.Table;
	actions: ActionDispatcher;
}

export default class Board extends React.Component<BoardProps> {
	render () {
		if (this.props.board != null) {
			return (
				// flex-direction: rowする
				<div className='board'>
					{this.props.board.arr.map(
						// 疑似要素で改行するのでCSSに
						(line, y) => (<div key={y} className='board-row'>{
							line.map(
								(square, x) => <Square square={square} key={y*100+x} pos={{x, y}}/>
							)
						}</div>)
					)}
				</div>
			);
		}
		else {
			return (
				<div></div>
			);
		}
	}
}

// server-gui/src/renderer/components/Board.vue
<template>
  <div class="board">
    <div class="row" v-for="line in tbl">
      <div
        class="square"
        v-for="square in line"
        v-bind:class="{ blue: square.color === 'Blue', red: square.color === 'Red' }"
      >
        {{ square.score }}
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: ['tbl'],
  name: 'board',
  data: () => ({}),
  methods: {
  },
};
</script>

<style>
.square {
  border: solid 1px #000000;
  height: 5vw;
  width: 5vw;
  text-align: center;
}
.row {
  display: flex;
  flex-direction: row;
}
.row:after {
  clear: both;
  content: "";
  display: table;
}
.board {
  display: flex;
  flex-direction: column;
}

.blue {
  background-color: #303F9F;
  color: #FFFFFF;
}

.red {
  background-color: #d32f2f;
  color: #FFFFFF;
}
</style>
